### PR TITLE
Change correct URL for downloading install data

### PR DESCRIPTION
**Pull request by insung3511**
Previous URL address was not incorrect. So I changed it.

### CODE REVIEW

**Comment by insung3511** [comment]
By the way, 6437f84 commit is not success to change correct.

**Comment by bemoody** [comment]
Thank you for pointing this out; it reminds me that we ought to update
this script for anyone who still wants to install XView.

What exactly did you try, and did it actually work?

**Comment by insung3511** [comment]
previous url address are response 404 error that mean not found files. So I just replace that working URL addresses

**Comment by insung3511** [comment]
And install-wave32.sh script is not working. just notice it

**Pull request merged**
